services:
  ollama-co2:
    build: .
    pull_policy: build
    container_name: ollama-co2
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      # Standard environment file
      - path: ./.env
        required: false
      # Portainer environment file
      - path: ./stack.env
        required: false
    restart: unless-stopped
